# Generated by Django 4.0.5 on 2022-08-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guestbook',
            table='guestBook',
        ),
    ]
