# Generated by Django 4.0.5 on 2022-08-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0002_alter_guestbook_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guestbook',
            table=None,
        ),
    ]
