# Generated by Django 4.0.5 on 2022-08-11 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0003_alter_guestbook_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 46, 8, 248011, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='name',
            field=models.CharField(default='익명', max_length=30),
        ),
    ]
