# Generated by Django 3.2.13 on 2022-08-11 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0003_alter_guestbook_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 17, 1, 19, 596197)),
        ),
        migrations.AlterField(
            model_name='guestbook',
            name='name',
            field=models.CharField(default='익명', max_length=30),
        ),
    ]
