<<<<<<< HEAD
# Generated by Django 3.2.13 on 2022-08-11 18:04

import datetime
=======
# Generated by Django 4.0.5 on 2022-08-12 04:13

>>>>>>> eb1d45d6addbd7c31287021d491a25dd80eedd7d
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('introduceapp', '0004_auto_20220811_1701'),
=======
        ('introduceapp', '0004_alter_guestbook_cdate_alter_guestbook_name'),
>>>>>>> eb1d45d6addbd7c31287021d491a25dd80eedd7d
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='cdate',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 4, 47, 946859)),
=======
            field=models.DateTimeField(auto_now_add=True),
>>>>>>> eb1d45d6addbd7c31287021d491a25dd80eedd7d
        ),
    ]
