# Generated by Django 3.2.13 on 2022-08-11 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0004_auto_20220811_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbook',
            name='cdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 18, 4, 47, 946859)),
        ),
    ]
