# Generated by Django 3.2.13 on 2022-08-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('introduceapp', '0004_alter_guestbook_cdate_alter_guestbook_name'),
        ('introduceapp', '0005_alter_guestbook_cdate'),
    ]

    operations = [
    ]
